---
name: untitled6
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.1.0
  flutter_splash_screen: ^1.0.0+6
  flutter_zoom_drawer: ^3.0.3
  flutter_native_splash: ^2.2.6
  expandable: ^5.0.1
  flutter_launcher_icons: ^0.9.3
  flutter_icons: ^1.1.0
  url_launcher: ^6.1.5
  advance_pdf_viewer: ^2.0.1
  path_provider: ^2.0.11
  path: ^1.8.1
  uc_pdfview: ^0.0.3
  alert: ^2.0.1
  intl: ^0.18.0
  firebase_core: ^2.7.1
  firebase_storage: ^11.0.15
  firebase_database: ^10.0.15
  change_app_package_name: ^1.1.0
  pdfx: ^2.3.0
#  icon: ^null
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_native_splash:
  color: '#FFFFFF'
  color_dark: '#FFFFFF'
  image: assets/logo3.png
  image_dark: assets/logo3.png
  android: true
  ios: true
flutter_icons:
  android: true
  ios: true
  image_path: assets/white.png
  adaptive_icon_background: assets/ps.png
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/texts/ecwa_anthem.txt
  - assets/texts/fellowship_covenant.txt
  - assets/texts/devotional.txt
